[theme]
primaryColor = "#4054A8"
backgroundColor = "#F7F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202440"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
